### PR TITLE
Django 1.10 compatibility needed

### PR DESCRIPTION
**Pull request by k8n**
Here is my first stab

### CODE REVIEW

**Comment by petrichuk** [comment]
Small change in readme:
 form  django.conf.urls import url
 from  django.conf.urls import url

**Comment by bashu** [comment]
@hedleyroos, @qoda can you take a look at this? thanks!

**Comment by felixxm** [comment]
@qoda, @hedleyroos Could you like at this? LGTM.

**Comment by Szuwar333** [comment]
@hedleyroos, @qoda It would be really helpful if you could merge this pull request. THX

**Comment by phala** [comment]
Hi @k8n @Szuwar333 @felixxm @petrichuk. 
Apologies for the delay. I will have a look at this tomorrow. Thanks guys!

**Comment by felixxm** [comment]
@phala Thanks for the reply. We really need a new version.

**Pull request merged**
